# -*- coding: utf-8 -*-
"""Students.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WFELjV1JjFYQvxxWB7U2FZrXRVhTifR8

**Students Performance on Test **
The aim of my analysis is to measure the effect of the following variables on students' performance:

1.   Gender
2.   Race
3.   Parental level of education

First we import & install the required packages. We choose color-blind friendly palette to help better visualization
"""

!pip install pingouin

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statistics as stat
import seaborn as sns
import  scipy.stats
from scipy.stats import t
import pingouin
sns.set_palette(palette="colorblind")

df = pd.read_csv("/content/drive/MyDrive/Data personal project/StudentsPerformance.csv")
df.head()

#Check if there is missing values
df.isna().sum()

#Summary statistcs for numerical variables
df.describe()

#Distribution of math score
g=sns.catplot(x="math score", data= df, kind="count", aspect=4)
g.fig.suptitle("Math Score Distribution")
g.set(xlabel="Math Score", ylabel="Count")
plt.xticks(np.arange(0, 120, step=10))
plt.show()

#Distribution of reading score
g=sns.catplot(x="reading score", data= df, kind="count",aspect=4)
g.fig.suptitle("Reading Score Distribution")
g.set(xlabel="Reading Score", ylabel="Count")
plt.xticks(np.arange(0, 120, step=10))


plt.show()

#Distribution of writing score
g=sns.catplot(x="writing score", data= df, kind="count",aspect=4)
g.fig.suptitle("Writing Score Distribution")
g.set(xlabel="Writing Score", ylabel="Count")
plt.xticks(np.arange(0, 120, step=10))
plt.show()

#Gender Vs Math Score
sns.boxplot(x="gender", y="math score", data = df)
plt.xlabel("Gender")
plt.ylabel("Math Score")
plt.title("Math Scores by Gender")
plt.show()

"""The previous plot show that the male students scored higher mean in Math. I will use T-test to determine in this difference is significant.The null hypothesis is no difference between the two groups. The alternative hypothesis is the female scores less than the males. alpha=0.05"""

xs=df.groupby('gender')['math score'].mean()
s =df.groupby('gender')['math score'].std()
ns =df.groupby('gender')['math score'].count()
print(xs, s, ns)
numerator=63.633205-68.728216
denominator= np.sqrt(15.491453**2/518)+(14.356277**2/482)
t_stat=numerator/denominator
print("t is ", t_stat)
print("p-value ",t.cdf(t_stat, df= (518+482)-2))

"""As we see the p-value is less than the significance level so we reject the null hypothesis and accept the hypothesis that males score more than females in Math"""

# Gender Vs Reading score
sns.boxplot(x="gender", y="reading score", data = df)
plt.xlabel("Gender")
plt.ylabel("Reading Score")
plt.title("Reading Scores by Gender")
plt.show()

"""The previous plot show that the female students scored higher mean in Reading. I will use T-test to determine in this difference is significant.The null hypothesis is no difference between the two groups. The alternative hypothesis is the female scores more than the males. alpha=0.05"""

xs=df.groupby('gender')['reading score'].mean()
s =df.groupby('gender')['reading score'].std()
ns =df.groupby('gender')['reading score'].count()
print(xs, s, ns)
numerator=72.608108-65.473029
denominator= np.sqrt(14.378245**2/518)+(13.931832**2/482)
t_stat=numerator/denominator
print("t is ", t_stat)
print("p-value ",1-t.cdf(t_stat, df= (518+482)-2))

"""As we see the p-value is less than the significance level so we reject the null hypothesis and accept the hypothesis that females score more than males in Reading"""

#Gender Vs Writing Score
sns.boxplot(x="gender", y="writing score", data = df)
plt.xlabel("Gender")
plt.ylabel("Writing Score")
plt.title("Writing Scores by Gender")
plt.show()

"""The previous plot show that the female students scored higher mean in Writinging. I will use T-test to determine in this difference is significant.The null hypothesis is no difference between the two groups. The alternative hypothesis is the female scores more than the males. alpha=0.05"""

xs=df.groupby('gender')['writing score'].mean()
s =df.groupby('gender')['writing score'].std()
ns =df.groupby('gender')['writing score'].count()
print(xs, s, ns)
numerator=72.467181-63.311203
denominator= np.sqrt(14.844842**2/518)+(14.113832**2/482)
t_stat=numerator/denominator
print("t is ", t_stat)
print("p-value ",1-t.cdf(t_stat, df= (518+482)-2))

"""As we see the p-value is less than the significance level so we reject the null hypothesis and accept the hypothesis that females score more than males in Reading"""

#Race vs Math Score
sns.boxplot(x="race/ethnicity", y="math score", data = df)
plt.xlabel("Race")
plt.ylabel("Math Score")
plt.title("Math Scores by Race")
plt.show()

#ANOVA Test to determine if the different Races has a Statistically Significant Difference(alpha=0.05)
pingouin.anova(data=df, dv="math score", between="race/ethnicity")

"""ANOVA p-value showed that at least two race group are significantly different so we will do pair wise test to discover"""

pairtest=pingouin.pairwise_tests(data=df, dv="math score", between="race/ethnicity", padjust="bonf")
significant_results = pairtest[pairtest['p-corr'] < 0.05]
print(significant_results)

"""As we can see Group E is signifcantly different from the other groups & there is also a significant difference between group A & D"""

#Race vs Reading Score
sns.boxplot(x="race/ethnicity", y="reading score", data = df)
plt.xlabel("Race")
plt.ylabel("Reading Score")
plt.title("Reading Scores by Race")
plt.show()

#ANOVA Test to determine if the different Races has a Statistically Significant Difference(alpha=0.05)
pingouin.anova(data=df, dv="reading score", between="race/ethnicity")

"""ANOVA p-value showed that at least two race group are significantly different so we will do pair wise test to discover"""

pairtest=pingouin.pairwise_tests(data=df, dv="reading score", between="race/ethnicity", padjust="bonf")
significant_results = pairtest[pairtest['p-corr'] < 0.05]
print(significant_results)

"""The results implies that Group E is significantly different (have a higher mean) from Group A, B. Also Group A is significantly different from Group D"""

#Race vs Writing Score
sns.boxplot(x="race/ethnicity", y="writing score", data = df)
plt.xlabel("Race")
plt.ylabel("Writing Score")
plt.title("Writing Scores by Race")
plt.show()

#ANOVA Test to determine if the different Races has a Statistically Significant Difference(alpha=0.05)
pingouin.anova(data=df, dv="writing score", between="race/ethnicity")

"""ANOVA p-value showed that at least two race group are significantly different so we will do pair wise test to discover"""

pairtest=pingouin.pairwise_tests(data=df, dv="writing score", between="race/ethnicity", padjust="bonf")
significant_results = pairtest[pairtest['p-corr'] < 0.05]
print(significant_results)

"""Group E & D are significantly different from Group A & B"""

#Heat map to determine correlation between the scores
sns.heatmap(df.corr(), annot=True)

"""It shows overall positive correlation between scores with strong correlation of 0.95 between reading & writing scores.

"""

df["total score"] = (df['math score']+df['reading score']+df['writing score'])/3

df.head()

#Box-plot for Parental Education vs Total Score
sns.boxplot(x="parental level of education", y="total score", data = df)
plt.xlabel("Parental level of Education")
plt.ylabel("Total Scores")
plt.title("Total Scores by Parental Education")
plt.xticks(rotation=45)
plt.show()

#ANOVA Test to determine if the different Parental education has a Statistically Significant Difference(alpha=0.05)
pingouin.anova(data=df, dv="total score", between="parental level of education")

"""ANOVA p-value showed that at least two groups are significantly different so we will do pair wise test to discover"""

pairtest=pingouin.pairwise_tests(data=df, dv="total score", between="parental level of education", padjust="bonf")
significant_results = pairtest[pairtest['p-corr'] < 0.05]
print(significant_results)

"""As we can see Group with high school education is signifcantly different from (associate's degree , bachelor's degree,master's degree & some college groups) & there is also a significant difference between bachelor's degree & some high schoolgroups"""

#Box-plot for Test preparation course vs Total Score
sns.boxplot(x="test preparation course", y="total score", data = df)
plt.xlabel("Test Preparation Course")
plt.ylabel("Total Scores")
plt.title("Total Scores by Test Preparation Course")
plt.xticks(rotation=45)
plt.show()

xs=df.groupby('test preparation course')['total score'].mean()
s =df.groupby('test preparation course')['total score'].std()
ns =df.groupby('test preparation course')['total score'].count()
print(xs, s, ns)
numerator=72.467181-63.311203
denominator= np.sqrt(14.844842**2/518)+(14.113832**2/482)
t_stat=numerator/denominator
print("t is ", t_stat)
print("p-value ",1-t.cdf(t_stat, df= (518+482)-2))

"""As we see the p-value is less than the significance level(alpha = 0.05) so we reject the null hypothesis and accept the hypothesis that the group that finished test preparation course scores higher than the group that did not took the course

**Final Conclusions :** Males score higher in Math , while females score higher in reading and writing . The Ethenic group E scores higher in all tests and was significantly different than Group A & B. Higher parental level of education is associated with higher scores. Test preparation coures help students to score higher grades
"""

